name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

jobs:
  Docker:
    runs-on: [self-hosted, linux, x64, multipass]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jerrythemyth/my-typescript-app:latest
