name: CI/CD Pipeline

on:
  push:
    branches:
      - JasaroskaAdrian-patch-1 

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jerrythemyth
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jerrythemyth/my-typescript-app:1.0.1
